### ISSUE TITLE
Crash when player moves open backpack in inventory on fabric 1.20.1 server.

### ISSUE THREAD

**Issue by Fnafacado** [Salandora/SophisticatedCore#11]
Hello, our server is crashing when someone moves a backpack in their inventory that they have opened. We're on fabric 1.20.1 and this is the only issue we've had so far. Any help would be appreciated, thanks!

The mods we're using:

![modlist2](https://github.com/user-attachments/assets/c8f0037b-0a3f-4b3d-95a0-ebd9c7fd23a2)
![modlist1](https://github.com/user-attachments/assets/c389796c-095d-493b-8b3a-363209b94b44)
![modlist0](https://github.com/user-attachments/assets/cd265574-da16-466f-815c-03ce79d35bec)

The log of the crash:

[22:38:46] [Server thread/INFO]: There are 2 of a max of 50 players online: CharlieBean_, Mommacado
[22:39:15] [Server thread/ERROR]: Error getting backpack wrapper - Unable to find backpack at slot index 6 in "main" inventory handler
[22:39:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: class net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase tried to access protected method 'void net.minecraft.class_1657.method_7346()' (net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @100fc185)
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.closeScreenIfSomethingMessedWithStorageItemStack(StorageContainerMenuBase.java:312) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.104.jar:?]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.method_7623(StorageContainerMenuBase.java:1428) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.104.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1695) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Salandora** [comment]
Yeah that's a known bug, I think it was reported in discord.
Fixed in fabric-dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
