### ISSUE TITLE
Sophisticated core conflicted whit Lithium

### ISSUE THREAD

**Issue by Desawe22** [Salandora/SophisticatedCore#5]
[Sophisticated Core](https://github.com/Salandora/SophisticatedCore/) is conflicting with [Lithium](https://github.com/CaffeineMC/lithium-fabric).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1937::port_lib$getBlockState with priority 1000 cannot inject into net/minecraft/class_1937::method_8320(Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; merged by me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> porting_lib/base.mixins.json:common.LevelMixin from mod sophisticatedcore -> Prepare Injections -> handler$hmp000$sophisticatedcore$port_lib$getBlockState(Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare ->  -> { target: method_8320(Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; }]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at net.minecraft.class_6396.handler$fdc000$patchouli$addContext(class_6396.java:1516)
	at net.minecraft.class_6396.<init>(class_6396.java:58)
	at net.minecraft.class_128.<init>(class_128.java:34)
	at net.minecraft.class_128.method_24305(class_128.java:274)
	at net.minecraft.client.main.Main.method_44604(Main.java:159)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- adaptive-tooltips 1.0.1
- advancedcompass 1.2.14
- advancementplaques 1.4.6
- adventurez 1.4.18
- animated_guns 1.2
- animatica 0.5+1.19
- antighost 1.19.1-fabric0.58.5-1.1.5
- appleskin 2.5.1+mc1.19
- arcanus 1.30
- architectury 6.6.92
- attributefix 17.2.8
- auditory 0.0.4-1.19.x
- automobility 0.4.2+1.19.2-fabric
- awesomedungeon 3.2.0
- awesomedungeonnether 3.1.1
- awesomedungeonocean 3.2.0
- balm-fabric 4.6.0
- bclib 2.1.8
- beachparty 1.0.12
- bendy-lib 2.1.3-test2 via emotecraft
- betteradvancements 0.2.2.142
- betterbiomeblend 1.19-1.3.6-fabric
- betterchunkloading 1.19.2-4.2
- bettercombat 1.7.1+1.19
- betterdungeons 1.19.2-Fabric-3.2.1
- betterend 2.1.7
- betterfpsdist 1.19.2-4.2
- bettermineshafts 1.19.2-Fabric-3.2.1
- betterstrongholds 1.19.2-Fabric-3.2.0
- bettervillage 3.1.0
- blue_endless_jankson 1.2.1 via doapi
- bobby 4.0.1
- bookshelf 16.3.20
- borderlessmining 1.1.5+1.19
- bosses_of_mass_destruction 1.4.8-1.19.2
- caffeineconfig 1.0.0+1.17 via sodium-extra
- capes 1.5.2+1.19.2
- cardinal-components 5.0.2
- cardinal-components-base 5.0.2
- cardinal-components-block 5.0.2 via cardinal-components
- cardinal-components-chunk 5.0.2 via cardinal-components
- cardinal-components-entity 5.0.2 via cardinal-components
- cardinal-components-item 5.0.2 via cardinal-components
- cardinal-components-level 5.0.2 via cardinal-components
- cardinal-components-scoreboard 5.0.2 via cardinal-components
- cardinal-components-world 5.0.2 via cardinal-components
- chunksending 1.19.2-2.8
- chunky 1.3.38
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.3.115
- coat 1.0.0-beta.19+mc22w17a via completeconfig
- collective 7.64
- com_electronwill_night-config_core 3.6.6 via corgilib
- com_electronwill_night-config_toml 3.6.6 via corgilib
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_github_zsoltmolnarrr_tinyconfig 2.3.2 via dungeon_difficulty
- com_typesafe_config 1.4.2 via bobby
- combatroll 1.1.5+1.19
- comforts 6.0.7+1.19.2
- completeconfig 2.1.0
- completeconfig-base 2.1.0 via completeconfig
- completeconfig-gui-cloth 2.1.0 via completeconfig
- completeconfig-gui-coat 2.1.0 via completeconfig
- completeconfig-gui-yacl 2.1.0 via completeconfig
- conditional-mixin 0.3.0 via cull-less-leaves
- config2brigadier 1.2.1 via taterzens
- continuity 2.0.2+1.19
- corgilib 1.0.0.34
- couplings 1.9.1+1.19
- creativecore 2.9.3
- crowdin-translate 1.4+1.19 via antighost
- cull-less-leaves 1.0.6
- cupboard 1.19.2-2.6
- deathcounter 1.4.0
- debugify 2.8.0
- deepslatecutting 1.5.0
- dev_isxander_settxi_settxi-core 2.10.5 via zoomify
- dev_isxander_settxi_settxi-gui 2.10.5 via zoomify
- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5 via zoomify
- doapi 1.1.0
- drinkbeer 3.2.2-1.19.2
- dungeon_difficulty 2.0.5+1.19
- dungeon_now_loading 1.0.0
- dungeons_arise 2.1.54
- dynamic_fps 3.6.0
- eatinganimationid 1.9.1
- eldritch_mobs 1.13.2
- emotecraft 2.2.7-b.build.50
- enchdesc 13.0.14
- endrem 5.2.0
- entity_texture_features 6.0.1
- entitycollisionfpsfix 2.0.0.0
- entityculling 1.6.1-mc1.19.2
- error_notifier 1.0.9 via roughlyenoughitems
- fabric-api 0.77.0+1.19.2
- fabric-api-base 0.4.15+8f4e8eb390 via fabric-api
- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 via fabric-api
- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
- fabric-containers-v0 0.1.42+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.9+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.11.0+kotlin.2.0.0
- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.12+def3f86d90 via fabric-api
- fabric-networking-v0 0.3.29+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
- fabric-particles-v1 1.1.0+ee641e7390 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via taterzens
- fabric-recipe-api-v1 1.0.2+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.33+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.1+1adbf27790 via fabric-api
- fabric-renderer-indigo 0.8.0+1adbf27790 via fabric-api
- fabric-renderer-registries-v1 3.2.25+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.28+df3654b390 via fabric-api
- fabric-rendering-v1 1.13.0+526f2c6790 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.4+edbdcddb90 via fabric-api
- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.16.0
- fake-player-api 0.4.0 via indrev
- fallingleaves 1.13.0+1.19.2
- farmersdelight 1.19.2-1.3.10.2
- farsight 1.19.2-3.5
- ferritecore 5.0.3
- fiber 0.23.0-2 via patchouli
- forgeconfigapiport 4.2.11
- fwaystones 3.0.8+mc1.19.2
- geckolib3 3.1.40
- graveyard 2.3.3
- guardvillagers 2.0.7-1.19.2
- highlighter 1.1.4
- hookshot 26.0
- iceberg 1.0.46
- ichunutil 1.0.0
- immediatelyfast 1.2.18+1.19.2
- immersive_aircraft 0.7.9+1.19.2
- immersive_armors 1.5.6+1.19.2
- immersive_paintings 0.6.7+1.19.2
- indium 1.0.9+mc1.19.2
- indrev 1.15.1-BETA
- interactic 0.1.11+1.19
- inventorysorter 1.8.10-1.19
- io_github_douira_glsl-transformer 2.0.0-pre13 via iris
- io_leangen_geantyref_geantyref 1.3.13 via bobby
- iris 1.6.6
- isxander-main-menu-credits 1.1.2
- itemmodelfix 1.0.3+1.19
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- jsonem 0.1.3+1.19 via automobility
- kanos_config 0.4.1+1.14.4-1.19.4 via pehkui
- kirin 1.11.1 via presencefootsteps
- kyrptconfig 1.4.14-1.19 via inventorysorter
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- languagereload 1.6.1+1.19.2
- lazydfu 0.1.3
- legendarytooltips 1.3.3
- libgui 6.0.0+1.19 via indrev
- libninepatch 1.1.0 via libgui
- libraryferret 4.0.0
- litematica 0.12.7
- lithium 0.11.1
- maelstrom_library 1.3.1-1.19.2 via bosses_of_mass_destruction
- magna 0.5.2-1.19.1 via indrev
- malilib 0.13.0
- maybe-data 1.3.2-1.19.2 via deepslatecutting
- mcwdoors 1.1.1
- midnightlib 1.0.0
- mimic 1.2.38
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixinextras 0.4.0 via fabricloader
- mixintrace 1.1.1+1.17
- mobplaques 4.0.1
- moonlight 1.19.2-2.3.6
- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
- mythicmounts 1.19.2-7.2
- naturalist 4.0.3
- net_lenni0451_reflect 1.3.4 via immediatelyfast
- net_lostluma_battery 1.0.1 via dynamic_fps
- nochatreports 1.19.2-v1.13.12
- noindium 1.0 via indrev
- notenoughanimations 1.7.4
- omega-config 1.2.3-1.18.1 via noindium
- optiglue 2.1.7-mc.1.19 via optigui
- optigui 2.1.7
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_commons_commons-text 1.10.0 via optigui
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_ini4j_ini4j 0.5.4 via optigui
- org_javassist_javassist 3.28.0-GA via yungsapi
- org_jctools_jctools-core 4.0.1 via farsight
- org_jetbrains_kotlin_kotlin-reflect 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_mariuszgromada_math_mathparser_org-mxparser 5.2.1 via immersive_aircraft
- org_reflections_reflections 0.10.2 via yungsapi
- org_spongepowered_configurate-core 4.1.2 via bobby
- org_spongepowered_configurate-hocon 4.1.2 via bobby
- owo 0.9.3+1.19
- packet_tweaker 0.3.0+1.18.2 via polymer
- patchouli 1.19.2-77-FABRIC
- pehkui 3.8.3+1.14.4-1.21
- pfm 1.2.1
- phosphor 0.8.1
- player-animator 1.0.2
- plentyofarmors 1.3.0
- polymer 0.2.28+1.19.2 via eldritch_mobs
- polymer-blocks-ext 0.1.0-alpha.9+1.19.2 via eldritch_mobs
- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
- porting_lib 2.3.0+1.20.1
- porting_lib_accessors 2.1.1305+1.19.2 via porting_lib_extensions
- porting_lib_attributes 2.1.1305+1.19.2 via porting_lib_extensions
- porting_lib_common 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_constants 2.1.1305+1.19.2 via porting_lib_extensions
- porting_lib_extensions 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_fake_players 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_lazy_registration 2.1.1305+1.19.2 via porting_lib_loot
- porting_lib_loot 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_model_loader 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_networking 2.1.1305+1.19.2 via sophisticatedbackpacks
- porting_lib_transfer 2.1.1305+1.19.2 via sophisticatedbackpacks
- presencefootsteps 1.6.4
- pride 1.1.2+1.19 via lambdynlights
- prism 1.0.3
- projectile_damage 3.2.1+1.19
- puzzle 1.4.2-1.19
- puzzle-base 1.4.2-1.19 via puzzle
- puzzle-gui 1.4.2-1.19 via puzzle
- puzzle-models 1.4.2-1.19 via puzzle
- puzzle-splashscreen 1.4.2-1.19 via puzzle
- puzzleslib 4.4.3
- reach-entity-attributes 2.3.0 via rottencreatures
- reeses-sodium-options 1.6.4+mc1.19.2-build.93
- rottencreatures 1.0.1
- roughlyenoughitems 9.2.724
- ruined_equipment 2.0.0
- server_translations_api 1.4.18+1.19.2 via eldritch_mobs
- settxi-gui-yacl 2.10.5 via zoomify
- sgui 1.1.3+1.19.1 via taterzens
- shulkerboxtooltip 3.2.2+1.19.2
- simplyswords 1.47.0-1.19.2
- smallships 2.0.0-b1.3.1
- smoothboot 1.19-1.7.1
- sodium 0.4.4+build.18
- sodium-extra 0.4.16+mc1.19.2-build.90
- sophisticatedbackpacks 3.19.5+mc1.19.2-SNAPSHOT-build.103
- sophisticatedcore 0.5.109+mc1.19.2-SNAPSHOT-build.103
- sophisticatedstorage 0.8.60+mc1.19.2-SNAPSHOT-build.103
- soulsweapons 1.1.3-1.19.2-fabric
- spectrelib 0.12.8+1.19.2 via comforts
- spiderstpo 1.19.2-2.0.3
- spruceui 4.1.0+1.19.2 via lambdynlights
- step-height-entity-attribute 1.0.0 via indrev
- stoneholm 1.4.4
- structory 1.0.1
- supplementaries 1.19.2-2.4.21
- taterzens 1.11.1
- team_reborn_energy 2.3.0 via sophisticatedbackpacks
- terraform-wood-api-v1 4.2.0 via doapi
- terralith 2.3.12
- tlc 1.0.0
- tradernpcs 1.2.0
- travelerstitles 1.19.2-Fabric-3.1.0
- trinkets 3.4.2
- tweakeroo 0.14.3
- villagernames 7.3
- visuality 0.5.6
- xaeroworldmap 1.38.8
- yet-another-config-lib 2.2.0-for-1.19.2
- yigd 1.4.9
- yosbr 0.1.2
- yungsapi 1.19.2-Fabric-3.8.10
- zoomify 2.9.0
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.16.0

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by Salandora** [comment]
Fixed in dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
